"""Validate the curated Tower MM snapshot and refresh the bundled UI lookup."""
import json
from pathlib import Path
import re

ROOT = Path(__file__).parent

def build():
    data = json.loads((ROOT / 'data/tower-masteries.json').read_text())
    catalog = json.loads((ROOT / 'data/catalog.json').read_text())['items']
    assert sorted(map(int, data['levels'])) == list(range(201, 341))
    lookup = {}
    for level, ids in data['levels'].items():
        assert len(ids) == len(set(ids)), f'Duplicate item at {level}'
        for item_id in ids:
            assert str(item_id) in catalog, f'Unknown item {item_id}'
            lookup.setdefault(str(item_id), []).append(int(level))
    gm = {}
    for level, ids in data.get('gm_levels', {}).items():
        for item_id in ids:
            assert str(item_id) in catalog
            gm.setdefault(str(item_id), []).append(int(level))
    bundle = dict(source=data['source'], verified_at=data['verified_at'], items=lookup, gm_items=gm)
    path = ROOT / 'web/app.js'
    text = path.read_text(encoding='utf-8')
    text, count = re.subn(r'globalThis.TOWER_MM = .*?;\n', 'globalThis.TOWER_MM = '+json.dumps(bundle, separators=(',', ':'))+';\n', text, count=1)
    assert count == 1
    text = text.replace('// Specific MM requirements, keyed by item ID; awaiting verified Tower MM library data.', '// Generated by build_tower_badges.py from data/tower-masteries.json.')
    path.write_text(text, encoding='utf-8')
    print(f'Bundled {len(lookup)} MM items across Tower 201–340 (GM-only requirements excluded).')

if __name__ == '__main__':
    build()
