const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('web/app.js','utf8'),nodes={};
const ctx={selected:0,fmt:String,esc:String,itemName:(id,name)=>name,$:id=>nodes[id]??={classList:{remove(){}}}};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('function implicitRows('),source.indexOf('function unused(')),ctx);
const plan={targets:[{item_id:'goal'}],crafts_in_dependency_order:[{item_id:'middle',name:'Middle',crafts:3},{item_id:'goal',name:'Goal',crafts:5}],secondary:{targets:[{item_id:'extra'}],crafts_in_dependency_order:[{item_id:'middle',name:'Middle',crafts:4},{item_id:'extra',name:'Extra',crafts:8},{item_id:'zero',name:'Zero',crafts:0}]},item_balances:[]};
const before=JSON.stringify(plan);ctx.implicitRows(plan);const html=nodes.implicitCrafts.innerHTML;
assert.match(html,/Ingredients crafted along the way/);assert.match(html,/Middle/);assert.match(html,/>7 /);assert.doesNotMatch(html,/Goal|Extra|Zero/);assert.equal(JSON.stringify(plan),before);
vm.runInContext(source.slice(source.indexOf('function routeTransition('),source.indexOf("$('routeCards').onclick")),ctx);
const route={continuous:false,parts:[{}],slots:5,craftStops:[{id:'x',sets:[[],[]],recipes:['a','b']}]};
const arrow=ctx.routeTransition(route,{id:'x'},0);assert.match(arrow,/data-craft-stop="x"/);assert.match(arrow,/<small>2<\/small>/);assert.match(arrow,/Repeat loop/);
assert.doesNotMatch(ctx.routeTransition({...route,continuous:true},{id:'x'},0),/data-craft-stop/);
console.log('Implicit craft aggregation and route checkpoint UI checks passed');
ctx.consumers=[{id:'indirect',name:'A indirect',direct:false},{id:'direct',name:'Z direct',direct:true}];ctx.state={secondary:[],targets:{}};nodes.consumerSearch={value:''};
vm.runInContext(source.slice(source.indexOf('function consumerList('),source.indexOf("$('consumerSearch').oninput")),ctx);
ctx.consumerList();assert.ok(nodes.consumerList.innerHTML.indexOf('Z direct')<nodes.consumerList.innerHTML.indexOf('A indirect'));
assert.match(nodes.consumerList.innerHTML,/Direct crafts/);assert.match(nodes.consumerList.innerHTML,/Indirect crafts/);
nodes.consumerSearch.value='indirect';ctx.consumerList();assert.doesNotMatch(nodes.consumerList.innerHTML,/Z direct/);
vm.runInContext(source.slice(source.indexOf('function mmBadge('),source.indexOf('function itemName(')),ctx);
ctx.TOWER_MM={items:{sample:[201,250]},gm_items:{}};assert.match(ctx.mmBadge('sample'),/201, 250/);assert.equal(ctx.mmBadge('unknown'),'');
console.log('Direct/indirect grouping, filtering, and MM badge lookup checks passed');
vm.runInContext(source.match(/globalThis.TOWER_MM = .*?;/)[0],ctx);
assert.equal(Object.keys(ctx.TOWER_MM.items).length,196);
assert.match(ctx.mmBadge('837'),/332/); // Linked Lantern MM, not merely a Tower reward.
assert.match(ctx.mmBadge('83'),/340/); // Purple Diary, separate MM column after T300.
assert.equal(ctx.mmBadge('11').includes('275'),true);
const catalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8')).items;
const crown=Object.values(catalog).find(i=>i.name==='Crown of Clover');
assert.match(ctx.mmBadge(crown.id),/>GM</);assert.doesNotMatch(ctx.mmBadge(crown.id),/>MM</);
assert.match(ctx.mmBadge(crown.id),/Required for Tower Level 306/);
console.log('Verified Tower MM snapshot checks passed');
vm.runInContext(source.slice(source.indexOf('function availableUnused('),source.indexOf('function unused(')),ctx);
assert.equal(ctx.availableUnused({expected_unused:0,reserved_secondary_output:137965}),137965);
assert.equal(ctx.availableUnused({expected_unused:12,reserved_secondary_output:30,used_by_leftover_craft:20}),42);
assert.equal(ctx.availableUnused({expected_unused:0,reserved_secondary_output:0,crafted:526,used_by_leftover_craft:526}),0);
assert.equal(ctx.availableUnused({expected_unused:2,reserved_target_output:100}),2);
console.log('Available finished outputs included without double-counting consumed crafts or primary goals');
vm.runInContext(source.slice(source.indexOf('function craftingIngredientIds('),source.indexOf('function unused(')),ctx);
ctx.items={wood:{direct_ingredients:{}},board:{direct_ingredients:{wood:5}},collectible:{direct_ingredients:{}}};
assert.deepEqual(Array.from(ctx.craftingIngredientIds()),['wood']);
vm.runInContext(source.slice(source.indexOf('function renderNonCraftingDrops('),source.indexOf('function encodePlanCode(')),ctx);
ctx.renderNonCraftingDrops({item_balances:[{item_id:'wood',name:'Wood',expected_exploration_drops:10},{item_id:'collectible',name:'Collectible',expected_exploration_drops:7}]});
assert.match(nodes.nonCraftingDrops.innerHTML,/Collectible/);
assert.doesNotMatch(nodes.nonCraftingDrops.innerHTML,/>Wood</);
console.log('Crafting ingredient filtering and other-drop grouping checks passed');
