const {chromium}=require('C:/Users/psamo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage();await p.addInitScript(()=>{if(!localStorage.getItem('farm-workshop-v1'))localStorage.setItem('farm-workshop-v1',JSON.stringify({targets:{837:90000}}));});const fixture=fs.readFileSync('../../work/lantern-90001-result.json','utf8');await p.route('**/python-worker.js',r=>r.fulfill({contentType:'text/javascript',body:'onmessage=()=>postMessage({status:"complete",result:'+fixture+'});'}));await p.goto('http://127.0.0.1:8765/#explore',{waitUntil:'domcontentloaded'});await p.locator('#resultContent').waitFor({state:'visible'});await p.locator('.plansave').evaluate(e=>e.open=true);
await p.locator('#savedPlanName').fill('Lantern plan');await p.locator('#saveNamedPlan').click();assert.equal(await p.locator('#savedPlanList option').count(),2);
await p.locator('#target-837').fill('90001');await p.locator('#target-837').dispatchEvent('change');await p.locator('#savedPlanName').fill('Another plan');await p.locator('#saveNamedPlan').click();assert.equal(await p.locator('#savedPlanList option').count(),3);
await p.locator('#savedPlanName').fill('Renamed');await p.locator('#renameNamedPlan').click();assert.match(await p.locator('#savedPlanList').inputValue(),/.+/);
const first=await p.locator('#savedPlanList option').filter({hasText:'Lantern plan'}).getAttribute('value');await p.locator('#savedPlanList').selectOption(first);await p.locator('#loadNamedPlan').click();await p.waitForLoadState('domcontentloaded');await p.locator('#target-837').waitFor();assert.equal(await p.locator('#target-837').inputValue(),'90000');await p.locator('.plansave').evaluate(e=>e.open=true);assert.equal(await p.locator('#savedPlanList option').count(),4);
await p.locator('#savedPlanList').selectOption(first);p.once('dialog',d=>d.accept());await p.locator('#deleteNamedPlan').click();assert.equal(await p.locator('#savedPlanList option').count(),3);assert.equal(await p.locator('#target-837').inputValue(),'90000');
for(const width of [320,390,1280]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('.plansave').scrollIntoViewIfNeeded();await p.screenshot({path:'../../work/saved-plans-'+width+'.png'});}
console.log('PASS named save, rename, multiple snapshots, load across reload, automatic backup, delete and mobile layout');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
