const fs=require('fs'),assert=require('assert/strict');
const {buildCraftMap,towerOpportunity}=require('./web/craft-map-model.js');
const items=JSON.parse(fs.readFileSync('data/catalog.json','utf8')).items;
const id=name=>Object.values(items).find(i=>i.name===name).id;
const stock={'White Parchment':200,'Purple Flower':300,'Fern Leaf':300};
const plan={item_balances:Object.entries(stock).map(([name,q])=>({item_id:id(name),expected_unused:q,crafted:0})),areas:[]};
const drafts=['Purple Diary','Green Diary'].map(name=>({item_id:id(name),cap:100}));
const graph=buildCraftMap(items,plan,{targets:{},secondary:[]},drafts);
assert.equal(new Set(graph.nodes.map(n=>n.id)).size,graph.nodes.length);
assert.equal(graph.missing[id('Mushroom')],600);
assert.equal(graph.nodes.find(n=>n.id===id('Mushroom Paste')).draftCrafts,200);
assert.equal(graph.links.filter(l=>l.from===id('White Parchment')).length,2);
assert.equal(graph.links.filter(l=>l.from===id('Mushroom Paste')).length,2);
assert.equal(graph.missing[id('Feathers')]||0,0);
const partial=structuredClone(plan);partial.item_balances.push({item_id:id('Mushroom Paste'),expected_unused:50,crafted:0});
assert.equal(buildCraftMap(items,partial,{targets:{},secondary:[]},drafts).missing[id('Mushroom')],450);
assert.equal(towerOpportunity('x',330,{items:{x:[321,340]},gm_items:{x:[350]}}).level,340);
console.log('One node per item, shared ghost demand, intermediate stock, Tower ranking passed.');

const {layoutCraftMap}=require('./web/craft-map-model.js');
const old=layoutCraftMap([{id:'a',name:'Alpha',depth:1},{id:'z',name:'Zulu',depth:1}]);
const next=layoutCraftMap([{id:'a',name:'Alpha',depth:1},{id:'b',name:'Beta',depth:1},{id:'z',name:'Zulu',depth:1}],old);
assert.deepEqual(next.z,old.z);
assert.notEqual(next.b.y,next.z.y);
const {laneLayoutCraftMap}=require('./web/craft-map-model.js');
const ns=[{id:'a',location:'a',name:'Forest',kind:'area',depth:0},{id:'b',location:'b',name:'Black Rock Canyon',kind:'area',depth:0},...['shared','exclusive','crop','external','crafted'].map(id=>({id,name:id,kind:'item',depth:id==='crafted'?2:1,crafts:id==='crafted'?10:0}))];
const ls=[{from:'a',to:'shared'},{from:'b',to:'shared'},{from:'b',to:'exclusive'},{from:'exclusive',to:'crafted'}];
const lanes=laneLayoutCraftMap(ns,ls,{crop:{farm_produced:true}},['a','b']);
assert.equal(lanes.assignments.shared,'shared');
assert.equal(lanes.assignments.exclusive,'b');
assert.equal(lanes.assignments.crafted,'flow');
assert.equal(lanes.assignments.crop,'farming');
assert.equal(lanes.assignments.external,'other');
assert.equal(lanes.positions.b.y,lanes.positions.exclusive.y);
for(const lane of lanes.lanes){const members=ns.filter(n=>lanes.assignments[n.id]===lane.id);for(const n of members)assert.ok(lanes.positions[n.id].y>=lane.y&&lanes.positions[n.id].y+110<lane.y+lane.height);}
console.log('Source lanes, shared drops, farm supplies, recipe alignment and lane bounds passed.');

const mixed=laneLayoutCraftMap([...ns,{id:'twine',kind:'item',name:'Twine',depth:2,crafts:2}], [...ls,{from:'exclusive',to:'twine'},{from:'crop',to:'twine'}],{crop:{farm_produced:true}},['a','b']);
assert.ok(mixed.positions.twine.y>mixed.positions.exclusive.y);
assert.ok(mixed.positions.twine.y<mixed.positions.crop.y);
const crowded=laneLayoutCraftMap([...ns,...Array.from({length:6},(_,i)=>({id:'c'+i,name:'Craft'+i,kind:'item',depth:2,crafts:1}))],[...ls,...Array.from({length:6},(_,i)=>({from:'exclusive',to:'c'+i}))],{crop:{farm_produced:true}},['a','b']);
const ys=['crafted',...Array.from({length:6},(_,i)=>'c'+i)].map(id=>crowded.positions[id].y).sort((a,b)=>a-b);
for(let i=1;i<ys.length;i++)assert.ok(ys[i]-ys[i-1]>=141.99);
const {craftMapUsage}=require('./web/craft-map-model.js');
assert.equal(craftMapUsage({kind:'item',stock:100}),'unused');
assert.equal(craftMapUsage({kind:'item',stock:.4}),'fulfilled');
assert.equal(craftMapUsage({kind:'item',stock:0,missing:10}),'pending');
console.log('Floating crafts center between ingredients; crowded columns do not overlap; usage colors passed.');
const {craftMapCandidateGaps}=require('./web/craft-map-model.js');
const gapRows=craftMapCandidateGaps(items,plan,{targets:{},secondary:[]},[],id('Green Diary'),100);
assert.ok(gapRows.some(([ref,q])=>ref===id('Mushroom')&&q===300));
const stocked={...plan,item_balances:[...plan.item_balances,{item_id:id('Mushroom'),expected_unused:300,crafted:0}]};
assert.equal(craftMapCandidateGaps(items,stocked,{targets:{},secondary:[]},[],id('Green Diary'),100).length,0);
console.log('Candidate supplied/gap estimates passed.');
const {craftMapAddOptions,craftMapDependents}=require('./web/craft-map-model.js');
const supply=(entries)=>({areas:[],item_balances:Object.entries(entries).map(([name,q])=>({item_id:id(name),expected_unused:q,crafted:0}))});
const twineSupply=supply({Wood:10,Straw:100});
const modes=craftMapAddOptions(items,twineSupply,{targets:{},secondary:[]},[],id('Twine'),id('Straw'));
assert.deepEqual(modes,{all:50,available:10});
assert.equal(craftMapCandidateGaps(items,twineSupply,{targets:{},secondary:[]},[],id('Twine'),modes.available).length,0);
assert.ok(craftMapCandidateGaps(items,twineSupply,{targets:{},secondary:[]},[],id('Twine'),modes.all).some(([ref,q])=>ref===id('Wood')&&q===40));
const emeraldSupply=supply({Emerald:10,Stone:10,'Mushroom Paste':10});
const ringGraph=buildCraftMap(items,emeraldSupply,{iron_depot:true,targets:{},secondary:[]},[{item_id:id('Emerald Ring'),cap:10}]);
assert.deepEqual(ringGraph.missing,{});
assert.equal(ringGraph.nodes.find(n=>n.id===id('Iron Ring')).blocked,false);
assert.equal(ringGraph.nodes.find(n=>n.id===id('Stone')).stock,0);
const noPerk=buildCraftMap(items,emeraldSupply,{iron_depot:false,targets:{},secondary:[]},[{item_id:id('Emerald Ring'),cap:10}]);
assert.equal(noPerk.missing[id('Iron')],20);
const protectedGraph=buildCraftMap(items,emeraldSupply,{iron_depot:true,targets:{[id('Emerald Ring')]:10},secondary:[]});
assert.ok(protectedGraph.nodes.find(n=>n.id===id('Iron Ring')).protected);
assert.equal(craftMapDependents(items,[{item_id:id('Emerald Ring')}],id('Iron Ring')).length,1);
assert.equal(craftMapUsage({kind:'item',stock:100,voided:true}),'void');
console.log('Use-all/available amounts, free supplies, draft usage, primary protection and void styling passed.');
const {craftMapNodeLabels}=require('./web/craft-map-model.js');
assert.deepEqual(craftMapNodeLabels({kind:'item',protected:true,useVoid:true},[],[]),{requirement:'REQUIRED NODE',mode:'Use + Void'});
assert.deepEqual(craftMapNodeLabels({kind:'item',voided:true,useVoid:true},[],[]),{requirement:'OPTIONAL NODE',mode:'Void/Sell'});
assert.equal(craftMapNodeLabels({id:'area',kind:'area'},[{id:'raw',protected:true}],[{from:'area',to:'raw'}]).requirement,'REQUIRED NODE');
console.log('Requirement labels and explicit choice labels passed.');

const {visibleCraftMapGaps}=require('./web/craft-map-model.js');
assert.deepEqual(visibleCraftMapGaps([['a',1],['b',9.99],['c',10]]),[['c',10]]);
assert.equal(craftMapUsage({kind:'item',stock:0,missing:3}),'fulfilled');
