const assert=require('node:assert/strict');
const {explorationCosts,ciderEffectiveness}=require('./web/costs.js');
const locations=[{id:'a',base_drop_rate:.4},{id:'b',base_drop_rate:.2}];
const p={optimal_total_explores:2000,areas:[{location_id:'a',explores:1000},{location_id:'b',explores:1000}]};
let c=explorationCosts(p,locations,{lemon_squeezer:true,cinnamon:true,wanderer:33});
assert.ok(Math.abs(c.manual_stamina-1340)<1e-8);
assert.equal(c.rows.length,12);
assert.equal(c.rows[0].drinks,2); // Per-area rounding, not ceil(600/500).
assert.equal(c.rows.find(r=>r.method==='Cider'&&r.foods==='None').drinks,2);
const base=c.rows.find(r=>r.method==='Cider'&&r.foods==='None');
const neigh=c.rows.find(r=>r.foods==='Neigh');
assert.ok(Math.abs(neigh.stamina/base.stamina-.8)<1e-12);
assert.equal(c.rows.find(r=>r.foods==='Neigh + Cabbage Stew').drinks,neigh.drinks);
c=explorationCosts({optimal_total_explores:100000,areas:[{location_id:'a',explores:100000}]},locations,{lemon_squeezer:true,cider_rolls:{a:2000}});
assert.equal(c.rows[0].drinks,80);
assert.equal(c.rows[1].clicks,16);
assert.equal(c.rows.find(r=>r.foods==='Lemon Seltzer').seltzers,2);
assert.equal(c.rows.find(r=>r.method==='Cider').drinks,50);
assert.equal(c.rows.find(r=>r.foods==='Quandary Chowder + Lemon Seltzer').drinks,49);
assert.equal(c.rows.find(r=>r.foods==='Quandary Chowder + Lemon Seltzer').drinks_high,50);
assert.throws(()=>explorationCosts(p,locations,{wanderer:100}));
assert.equal(explorationCosts({optimal_total_explores:0,areas:[]},locations,{}).rows[0].drinks,0);
console.log('Exploration conversion checks passed.');
assert.equal(ciderEffectiveness({effectiveness_upgrades:{a:13},sprint_shoes:2,cinnamon:true},'a').rolls,1950);
assert.equal(ciderEffectiveness({effectiveness_upgrades:{a:14},sprint_shoes:2,cinnamon:true},'a').rolls,2000);
assert.equal(ciderEffectiveness({effectiveness_upgrades:{a:13},sprint_shoes:2},'a').effectiveness,56);
assert.equal(ciderEffectiveness({cider_rolls:{a:1732}},'a').rolls,1732);
assert.equal(ciderEffectiveness({cider_rolls:{a:1732},effectiveness_upgrades:{a:0}},'a').rolls,1010);
assert.throws(()=>ciderEffectiveness({effectiveness_upgrades:{a:-1}},'a'));
