const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const store=new Map(),c={TextEncoder,TextDecoder,btoa,atob,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}};
vm.createContext(c);vm.runInContext(fs.readFileSync('web/global-settings.js','utf8'),c);
const settings=c.GlobalSettings,locations=[{id:'forest'},{id:'cave'},{id:'explore:11'},{id:'explore:14'}];
const plain=value=>JSON.parse(JSON.stringify(value));
const legacy={targets:{a:100},inventory:'{"a":5}',theme:'light',resource_saver:45,areas:['forest'],craftworks_slots:22,inventory_size:20000,tower_level:250};
assert.deepEqual(plain(settings.initialize(legacy,locations)),{...plain(settings.defaults),...plain(settings.pick(legacy))});
assert.equal(settings.read().targets,undefined);assert.equal(settings.read().inventory,undefined);
settings.write({...settings.read(),resource_saver:15},locations);
assert.equal(settings.initialize(legacy,locations).resource_saver,15,'old local autosave cannot overwrite current settings after migration');
store.clear();assert.deepEqual(plain(settings.initialize(null,locations).areas),['forest','cave'],'fresh settings enable normal zones only');
settings.write({...legacy,areas:[]},locations);assert.deepEqual(plain(settings.read(locations).areas),[],'explicitly disabling all areas survives');
const code=settings.encode(legacy),roundtrip=settings.decode(code,locations);
assert.deepEqual(plain(roundtrip),{...plain(settings.defaults),...plain(settings.pick(legacy))});
assert.throws(()=>settings.decode('FW1.'+code.slice(5),locations));
assert.throws(()=>settings.write({...legacy,resource_saver:99},locations));
assert.equal(settings.read().resource_saver,45,'failed validation does not alter settings');
assert.throws(()=>settings.write({...legacy,runecube:'yes'},locations));
assert.throws(()=>settings.write({...legacy,effectiveness_upgrades:{forest:-1}},locations));
settings.defaults.future_perk=false;
assert.equal(settings.decode(code,locations).future_perk,false,'new fields get defaults');
const removed=settings.decode(settings.encode({...legacy,effectiveness_upgrades:{forest:3,removed:4},areas:['forest','removed']}),locations);
assert.deepEqual(plain(removed.areas),['forest']);assert.deepEqual(plain(removed.effectiveness_upgrades),{forest:3});
settings.writeProfiles([{id:'a',name:'Main farm',code,updated:1}]);
assert.equal(settings.readProfiles()[0].name,'Main farm');
assert.equal(settings.read().resource_saver,45,'saving profiles does not implicitly apply them');
store.set(settings.profilesKey,'{"version":1,"profiles":[{}]}');assert.throws(()=>settings.readProfiles());
assert.match(store.get(settings.profilesKey),/profiles/,'invalid libraries are preserved');
console.log('Global settings: one-time migration, independent storage, explicit empty zones, profile isolation, validated codes, new defaults and catalog changes passed.');
