/* Desktop-first map UI; the existing planner remains the authority for quantities. */
const craftMap=document.createElement('section');craftMap.id='craftMap';craftMap.className='panel craft-map';
craftMap.innerHTML=`<div class="map-header"><div><p class="eyebrow">FOLLOW THE MATERIALS</p><h2>Crafting map</h2></div><label>Tower level <input id="mapTower" type="number" min="0" max="10000" step="1" value="0"></label><button id="mapReviewTop" class="primary" disabled>Review &amp; apply changes</button><button id="mapNext" type="button">Next opportunity</button><button id="mapExpand" type="button">Expand map</button><button id="mapZoomOut" type="button" aria-label="Zoom out">−</button><button id="mapZoomIn" type="button" aria-label="Zoom in">+</button></div><div class="map-intro"><span>Click an item to use it. Add supplies where needed, then review your changes.</span><details class="map-help"><summary>Help</summary><p>Sources are on the left; your goals are on the right. Use + on an item to find recipes. Expand a location to see its unused drops.</p><p>Missing supplies appear at the top. Choose a source or bring the ingredients yourself. Changes stay in draft until you apply them.</p><p>Use + and − to zoom, and scroll to move around. Void/Sell accepts an item’s surplus without taking supplies away from your crafts.</p></details></div><div class="map-display-settings"><label>Top unused items <select id="mapUnusedMode"><option value="all">All</option><option value="top">Top X</option><option value="none">None</option></select></label><input id="mapUnusedCount" type="number" min="1" max="1000" step="1" value="6" aria-label="Number of top unused items"><span class="hint">Across the route. Expand a location for its other unused crafting materials. Needed ingredients stay visible.</span></div><div class="map-legend"><span class="legend-fulfilled">Fully used / goal met</span><span class="legend-unused">Items left to use</span><span class="legend-pending">Missing supplies / proposed craft</span></div><div class="map-workspace"><div id="mapViewport" class="map-viewport" tabindex="0" aria-label="Crafting graph"><div id="mapStage" class="map-stage"><div id="mapCanvas" class="map-canvas"><div id="mapLanes"></div><svg id="mapEdges" aria-hidden="true"></svg><div id="mapNodes"></div></div></div></div><aside id="mapInspector" class="map-inspector" aria-label="Selected item details"></aside></div><div class="map-footer"><span id="mapSummary" role="status"></span><span id="mapPending"></span><button id="mapPreview" type="button" class="primary" disabled>Review &amp; apply changes</button><button id="mapDiscard" type="button" disabled>Discard draft</button></div><dialog id="mapReviewDialog" aria-labelledby="mapReviewTitle"><div class="sectiontitle"><h2 id="mapReviewTitle">Review changes</h2><button id="mapCloseReview" type="button" aria-label="Close review">Close</button></div><p id="mapReviewStatus" role="status"></p><div id="mapPreviewResult" class="map-preview" hidden></div></dialog>`;
$('routePanel').after(craftMap);
let mapInspectDraft=null,mapOpenedOnce=false;
$('mapCloseReview').onclick=()=>$('mapReviewDialog').close();
let mapLaneSignature="";
let mapGraph=null,mapPlan=null,mapDrafts=[],mapExtraAreas=new Set(),mapExpanded=new Set(),mapPositions={},mapSelected=null,mapScale=1,mapJob=0,mapRevision=0,mapPreview=null,mapVisit=new Set(),mapProposedLinks=[],mapCandidateToken=0;
let mapOriginal=null;
function mapBeginEdit(){if(!mapOriginal)mapOriginal=JSON.parse(JSON.stringify({secondary:state.secondary,map_hidden:state.map_hidden,map_voided:state.map_voided,map_use_void:state.map_use_void}));}
function mapChangeCount(){return mapDrafts.length+(mapOriginal?1:0);}
function mapCount(q){return fmt(Math.floor(q||0));}
function mapCurrent(){return result?.plans?.[selected];}
function mapBusy(){return $('status').classList.contains('loading')||$('resultContent').classList.contains('stale');}
function mapChanged(){mapJob++;if(mapPreviewRunning){browserPlanner.cancel();mapPreviewRunning=false;}mapPreview=null;$('mapPreviewResult').hidden=true;mapRender();}
function mapRender(){
 const p=mapCurrent();if(!p){craftMap.hidden=true;return;}craftMap.hidden=false;if(!mapOpenedOnce){mapOpenedOnce=true;craftMap.classList.add('map-fullscreen');$('mapExpand').textContent='Back to planner';}
 if(mapPlan!==p){mapOriginal=null;mapPlan=p;mapDrafts=[];mapInspectDraft=null;mapExtraAreas.clear();mapProposedLinks=[];mapPreview=null;$('mapPreviewResult').hidden=true;}
 $('mapTower').value=state.tower_level||0;$('mapUnusedMode').value=state.map_unused_mode||'top';$('mapUnusedCount').value=state.map_unused_count??6;$('mapUnusedCount').hidden=(state.map_unused_mode||'top')!=='top';
 const solvedPreview=mapPreview?.preview_plan&&!mapPreview.shortfalls?.length;const shown=solvedPreview?mapPreview.preview_plan:p;
 mapGraph=buildCraftMap(items,shown,{...state,secondary:[...state.secondary,...(solvedPreview?mapDrafts:[])],map_use_void:[...state.map_use_void.filter(id=>!state.secondary.some(g=>g.item_id===id)),...mapDrafts.filter(g=>g.available_only).map(g=>g.void_source).filter(Boolean)]},[...(solvedPreview?[]:mapDrafts),...(mapInspectDraft?[mapInspectDraft]:[])],[...mapExpanded]);
 for(const draft of mapDrafts){const node=mapGraph.nodes.find(n=>n.id===draft.item_id);if(node&&solvedPreview)node.previewAim=draft.cap;}
 const activeGoals=[...state.secondary,...mapDrafts,...(mapInspectDraft?[mapInspectDraft]:[])];
 mapGraph.nodes=mapGraph.nodes.filter(n=>n.protected||n.explorationSupplied||!state.map_hidden.includes(n.id)||craftMapDependents(items,activeGoals,n.id).length);
 const visibleIds=new Set(mapGraph.nodes.map(n=>n.id));mapGraph.links=mapGraph.links.filter(l=>visibleIds.has(l.from)&&visibleIds.has(l.to));
 for(const id of mapExtraAreas){const area=catalog.locations.find(a=>a.id===id);if(!area||shown.areas.some(a=>a.location_id===id))continue;mapGraph.nodes.push({id:'area:'+id,location:id,kind:'area',name:area.name,depth:0,proposed:true,explores:0,outputs:[]});}
 for(const link of solvedPreview?[]:mapProposedLinks)if(mapGraph.nodes.some(n=>n.id===link.to))mapGraph.links.push(link);
 const layout=laneLayoutCraftMap(mapGraph.nodes,mapGraph.links,items,explorationMenuOrder);
 const signature=JSON.stringify([mapGraph.nodes.map(n=>[n.id,n.depth]),layout.assignments]);
 if(signature!==mapLaneSignature||!Object.keys(mapPositions).length){mapPositions=layout.positions;mapLaneSignature=signature;}
 $('mapLanes').innerHTML=layout.lanes.map(l=>`<div class="map-lane" style="top:${l.y}px;height:${l.height}px"><span>${esc(l.name)}</span></div>`).join('');
 const width=Math.max(1000,...mapGraph.nodes.map(n=>mapPositions[n.id].x+240)),height=Math.max(570,layout.height,...mapGraph.nodes.map(n=>mapPositions[n.id].y+126));
 $('mapCanvas').style.width=width+'px';$('mapCanvas').style.height=height+'px';$('mapEdges').setAttribute('width',width);$('mapEdges').setAttribute('height',height);
 $('mapNodes').innerHTML=mapGraph.nodes.map(n=>{
  const pos=mapPositions[n.id],area=catalog.locations.find(a=>a.id===n.location);
  const icon=n.kind==='item'?itemIcon(n.id):area?.image?`<img class="gameicon" src="${esc(area.image.startsWith('/')?'https://farmrpg.com'+area.image:area.image)}" alt="">`:'<span class="map-source-icon">⌖</span>';
  const label=n.kind==='item'?`${icon}<span>${esc(n.name)}</span>${mmBadge(n.id)}`:`${icon}<span>${esc(n.name)}</span>`;
  const badges=craftMapNodeLabels(n,mapGraph.nodes,mapGraph.links);
  const role=n.primary?'PRIMARY GOAL':n.draft?'PROPOSED CRAFT':n.secondary?'LEFTOVER CRAFT':n.missing>=10?'MISSING INGREDIENT':n.kind==='area'?(n.proposed?'PROPOSED LOCATION':'EXPLORATION'):n.kind==='inventory'?'SUPPLIES':n.free?'FREE WITH PERK':n.draftCrafts?'INTERMEDIATE NEEDED':'INGREDIENT';
  const detail=n.kind==='area'?(n.proposed?'Preview to calculate explores':mapCount(n.explores)+' explores'):n.kind==='inventory'?'Inventory and free perk supplies':n.free?'Unlimited':n.previewAim!=null?mapCount(n.crafts)+' / '+mapCount(n.previewAim)+' crafts':n.missing>=10?'':n.primary?mapCount(state.targets[n.id])+' wanted':n.draft?mapCount(n.draftCrafts)+' craft aim':n.draftCrafts?mapCount(n.draftCrafts)+' more crafts needed':n.secondary&&n.crafts<1?'0 crafts · supplies needed':n.crafts?mapCount(n.crafts)+' crafts · '+mapCount(n.stock)+' unused':mapCount(n.stock)+' unused';
  return `<article class="map-node ${n.kind} usage-${craftMapUsage(n)} ${n.primary?'goal':''} ${n.draft||n.warningBlocked||n.missing>=10||n.proposed?'phantom':''} ${mapSelected===n.id?'selected':''}" tabindex="0" aria-label="Inspect ${esc(n.name)}" data-map-node="${esc(n.id)}" style="left:${pos.x}px;top:${pos.y}px"><div class="map-node-handle"><span class="map-required-label ${badges.requirement==='REQUIRED NODE'?'required':'optional'}">${badges.requirement}</span><small>${role}</small></div><button class="map-node-label" data-map-open="${esc(n.id)}">${label}</button>${detail?`<p>${detail}</p>`:""}${n.missing>=10?`<button class="map-gap" data-map-gap="${esc(n.id)}" aria-label="Show missing ${esc(n.name)}">⚠ ${mapCount(Math.ceil(n.missing))} missing</button>`:""}${badges.mode?`<div class="map-choice-label">${badges.mode}</div>`:""}${n.kind==='area'&&!n.proposed?`<button class="map-area-toggle" data-map-toggle-area="${esc(n.location)}" aria-expanded="${(state.map_expanded_areas||[]).includes(n.location)}">${(state.map_expanded_areas||[]).includes(n.location)?'− Collapse extra items':'+ Show all unused'}</button>`:''}${n.kind==='item'?`<button class="map-port" data-map-port="${esc(n.id)}" aria-label="Choose a craft using ${esc(n.name)}" title="Choose a craft">+</button>`:''}</article>`;
 }).join('');
 $('mapNodes').querySelectorAll('[data-item-info]').forEach(el=>{el.removeAttribute('data-item-info');if(el.tagName==='IMG')el.draggable=false;});mapDrawEdges();mapZoom(mapScale);
 $('mapSummary').textContent=`${mapPreview?.preview_plan?'Preview: ':''}${mapCount(shown.optimal_total_explores)} explores · ${shown.areas.length} locations · ${mapGraph.nodes.filter(n=>n.primary).length} primary goals`;
 $('mapPending').textContent=mapChangeCount()?`${mapChangeCount()} changes not applied · ${visibleCraftMapGaps(Object.entries(mapGraph.missing)).length} missing materials`:'';
 $('mapPreview').disabled=!mapChangeCount()||mapBusy();$('mapDiscard').disabled=!mapChangeCount()&&!mapInspectDraft;$('mapReviewTop').disabled=$('mapPreview').disabled;$('mapReviewTop').textContent=mapChangeCount()?'Review & apply '+mapChangeCount()+' changes':'Review & apply changes';
 if(!mapSelected)$('mapInspector').innerHTML='<h3>Put your leftovers to work</h3><p>Click an item to see your options, or try Next opportunity.</p>';
}
function mapDrawEdges(){
 if(!mapGraph)return;const curves=mapGraph.links.filter(l=>mapPositions[l.from]&&mapPositions[l.to]);
 $('mapEdges').innerHTML='<defs><marker id="mapArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="currentColor"/></marker></defs>'+curves.map(l=>{const a=mapPositions[l.from],b=mapPositions[l.to],x=a.x+206,y=a.y+60,end=b.x,ey=b.y+60,mid=(x+end)/2;return `<path class="${l.phantom?'pending':''}" d="M${x},${y} C${mid},${y} ${mid},${ey} ${end},${ey}" marker-end="url(#mapArrow)"><title>${l.quantity>0?mapCount(l.quantity)+' items':'Recipe connection — no current consumption'}</title></path>`;}).join('');
}
function mapSelect(id){mapSelected=id;mapCandidateToken++;mapRender();const n=mapGraph.nodes.find(n=>n.id===id);if(!n)return;
 if(n.kind==='area'){const outputs=n.outputs||[];$('mapInspector').innerHTML=`<h3>${esc(n.name)}</h3><p>${n.proposed?'Proposed extra source. The solver will calculate the amount.':mapCount(n.explores)+' expected explores'}</p><p class="hint">Show an output to connect it to this location. Each item appears only once in the map.</p>${outputs.sort((a,b)=>b.expected_drops-a.expected_drops).map(o=>`<button class="map-output" data-map-reveal="${esc(o.item_id)}">${itemName(o.item_id,items[o.item_id]?.name||o.item_id)}<strong>${mapCount(o.expected_drops)}</strong></button>`).join('')}`;return;}
 if(n.kind==='inventory'){$('mapInspector').innerHTML='<h3>Starting supplies</h3><p>These come from Starting inventory, passive production, or free perk supplies. Change their amounts in the existing input controls.</p>';return;}
 const opportunity=towerOpportunity(id,state.tower_level||0,globalThis.TOWER_MM),draft=mapDrafts.find(g=>g.item_id===id),applied=state.secondary.find(g=>g.item_id===id);
 $('mapInspector').innerHTML=`<h3>${itemName(id,n.name)}</h3>${opportunity?`<p class="map-tower-note">${opportunity.type} · Tower ${opportunity.level} · ${opportunity.level>(state.tower_level||0)?opportunity.level-(state.tower_level||0)+' levels ahead':'Earlier requirement'}</p>`:''}<p>${n.free?'Unlimited perk supply':mapCount(n.stock)+' unused after draft crafts'}${n.need?` · ${mapCount(Math.ceil(n.need))} needed by proposed crafts`:''}</p>${mapChangeCount()?'<p class="map-draft-note">Changes aren’t applied yet. Review them when you’re ready.</p>':''}${mapInspectDraft?`<div class="map-gap-list">${craftMapCandidateGaps(items,mapPlan,state,mapDrafts,mapInspectDraft.item_id,mapInspectDraft.cap).filter(([,q])=>q>=10).map(([ref,q])=>`<button class="map-gap" data-map-jump="${ref}">⚠ ${mapCount(Math.ceil(q))} ${esc(items[ref].name)} missing →</button>`).join('')}</div><p class="map-draft-note">Checking ${esc(items[mapInspectDraft.item_id].name)}; not added yet.</p><button data-map-add="${mapInspectDraft.item_id}" data-map-quantity="${mapInspectDraft.cap}" data-map-custom="${!!mapInspectDraft.automatic_supply}">Add this craft to draft</button>`:''}${draft?`<label>Maximum crafts <input id="mapDraftQuantity" type="number" min="1" max="100000000" step="1" value="${draft.cap}"></label>`:''}${applied&&!draft?`<label>Maximum crafts <input id="mapAppliedCap" type="number" min="0" max="100000000" step="1" placeholder="No cap" value="${applied.cap??''}"></label>${n.crafts<1?'<p class="map-gap">Not enough supplies to craft this yet. Dashed links show its ingredients.</p>':''}`:''}${n.missing>=10?`<div class="map-gap">⚠ ${mapCount(Math.ceil(n.missing))} ${esc(n.name)} missing</div><button id="mapFindSources" class="primary">Find exploration sources</button><p class="hint">Choose an exploration source or add what you already have in Settings.</p>`:''}<button id="mapFindCrafts" class="primary">Choose a craft using this</button>${n.explorationSupplied?'<p class="hint">Your route collects this item. Use Void/Sell if you don’t need the surplus.</p>':n.protected?'<p class="hint">Needed for your target. Change the target to remove it.</p>':`<button id="mapDeleteNode">Delete node</button>`}<button id="mapVoidNode">${n.voided?'Undo Void/Sell':'Void/Sell'}</button><p class="hint">Void/Sell leaves the surplus unused. Your crafts still get what they need.</p><div id="mapOptions"></div>`;
 $('mapFindCrafts').onclick=()=>mapConsumers(id);if($('mapFindSources'))$('mapFindSources').onclick=()=>mapSources(id);
 $('mapVoidNode').onclick=()=>{mapBeginEdit();if(n.voided)for(const g of mapDrafts)if(g.void_source===id)g.void_source=null;state.map_voided=n.voided?state.map_voided.filter(ref=>ref!==id):[...new Set([...state.map_voided,id])];mapChanged();mapSelect(id);};
 if($('mapDeleteNode')){
  const affected=craftMapDependents(items,[...state.secondary,...mapDrafts],id);
  $('mapDeleteNode').textContent=affected.some(ref=>ref!==id)?'Delete node and dependent crafts':'Delete node';if(affected.some(ref=>ref!==id))$('mapDeleteNode').insertAdjacentHTML('afterend',`<p class="hint">Also removes: ${affected.map(ref=>esc(items[ref].name)).join(', ')}. They cannot be crafted without this ingredient.</p>`);
  $('mapDeleteNode').onclick=()=>{if(n.protected||n.explorationSupplied)return;mapBeginEdit();mapInspectDraft=null;mapExpanded.delete(id);state.map_hidden=[...new Set([...state.map_hidden,id])];mapDrafts=mapDrafts.filter(g=>!affected.includes(g.item_id));state.secondary=state.secondary.filter(g=>!affected.includes(g.item_id));mapSelected=null;mapChanged();};
 }
 if(applied&&!draft){
  $('mapAppliedCap').onchange=async e=>{const raw=e.target.value,q=raw===''?null:Number(raw);if(q!==null&&(!Number.isInteger(q)||q<0||q>100000000))return;mapBeginEdit();applied.cap=q;mapChanged();if(mapSelected)mapSelect(mapSelected);};
 }
 if(draft)$('mapDraftQuantity').onchange=e=>{const q=Number(e.target.value);if(!Number.isInteger(q)||q<1||q>100000000)return;draft.cap=q;mapChanged();mapSelect(id);};
}
async function mapConsumers(id){
 const token=++mapCandidateToken,host=$('mapOptions');host.textContent='Finding crafts…';
 try{const rows=await api('/api/consumers/'+id);if(token!==mapCandidateToken)return;
  const stock=Object.fromEntries(mapPlan.item_balances.map(b=>[b.item_id,Math.max(0,b.expected_unused||0)]));
  const estimates=suggestCrafts(items,stock,state,id,1000,true),byId=new Map([...estimates.explore,...estimates.ready].map(r=>[r.id,r]));
  const chosen=new Set([...Object.keys(state.targets),...state.secondary.map(g=>g.item_id),...mapDrafts.map(g=>g.item_id)]);
  const level=state.tower_level||0;
  const rank=r=>{const badge=towerOpportunity(r.id,level,globalThis.TOWER_MM);return badge&&badge.level>level?badge.level-level:100000;};
  const options=rows.filter(r=>!chosen.has(r.id)).sort((a,b)=>rank(a)-rank(b)||(byId.get(b.id)?.score||0)-(byId.get(a.id)?.score||0)||Number(b.direct)-Number(a.direct));
  host.innerHTML=`<h4>Use ${esc(items[id].name)}</h4><p class="hint">Upcoming Tower requirements first, then use of existing supplies. Choose a craft to draw its inputs before exploring more.</p><input id="mapCraftFilter" placeholder="Filter crafts…" aria-label="Filter map crafts"><div id="mapCraftList"></div>`;
  function listing(){const q=$('mapCraftFilter').value.toLowerCase();$('mapCraftList').innerHTML=options.filter(r=>r.name.toLowerCase().includes(q)).slice(0,40).map(r=>{const estimate=byId.get(r.id),badge=towerOpportunity(r.id,level,globalThis.TOWER_MM);const addOptions=craftMapAddOptions(items,mapPlan,state,mapDrafts,r.id,id),quantity=addOptions.all,gaps=visibleCraftMapGaps(craftMapCandidateGaps(items,mapPlan,state,mapDrafts,r.id,quantity));
 const warningRows=gaps.length?gaps.slice(0,2).map(([ref,q])=>`<button class="map-gap" data-map-choice-gap="${r.id}" data-map-quantity="${quantity}" data-map-missing="${ref}">⚠ ${mapCount(Math.ceil(q))} ${esc(items[ref].name)} missing →</button>`).join('')+(gaps.length>2?`<button class="map-gap" data-map-choice-gap="${r.id}" data-map-quantity="${quantity}" data-map-missing="${gaps[2][0]}">⚠ ${gaps.length-2} more ingredient gaps →</button>`:''):'<p class="map-supplied">✓ No significant ingredient gaps</p>';
 return `<div class="map-choice"><div class="map-candidate">${itemName(r.id,r.name)}<small>${r.direct?'Direct craft':'Through intermediates'}${badge&&badge.level>level?' · Tower '+badge.level+' ahead':''}</small></div><div class="map-add-actions"><section class="map-add-option" aria-label="Use all option"><button data-map-add="${r.id}" data-map-quantity="${quantity}" data-map-focus="${id}">Force Use All · ${mapCount(quantity)} crafts</button><p class="hint">Use this material completely. Supply the gaps below.</p>${warningRows}</section><section class="map-add-option map-custom-option" data-map-custom-item="${r.id}"><label class="map-custom-label">Make up to <span class="map-custom-controls"><input type="number" min="1" max="100000000" step="1" value="10000" aria-label="Maximum crafts for ${esc(r.name)}"><button data-map-add="${r.id}" data-map-custom="true" data-map-quantity="10000">Add</button></span></label><div class="map-quantity-presets">${[1000,5000,10000,100000].map(n=>`<button data-map-preset="${n}">${n/1000}k</button>`).join('')}<span>crafts</span></div><p class="hint">Set a craft limit, then choose sources for any missing ingredients on the map.</p><div class="map-custom-gaps"></div></section><section class="map-add-option" aria-label="Use available option"><button data-map-add="${r.id}" data-map-quantity="${addOptions.available}" data-map-focus="${id}" data-map-available="true" ${addOptions.available?'':'disabled'}>Use + Void · ${mapCount(addOptions.available)} crafts</button>${addOptions.available?'<p class="map-supplied">✓ No extra exploring. Accept the remaining material.</p>':'<p class="map-gap">⚠ Current supplies cannot make one complete craft.</p>'}</section></div></div>`;}).join('')||'<p>No new crafts match.</p>';}
  $('mapCraftFilter').oninput=()=>{listing();mapRefreshCustomOptions();};listing();mapRefreshCustomOptions();
 }catch(e){if(token===mapCandidateToken)host.textContent=e.message;}
}
function mapRefreshCustomOptions(section){
 for(const box of section?[section]:$('mapInspector').querySelectorAll('.map-custom-option')){
  const input=box.querySelector('input'),q=Number(input.value),button=box.querySelector('[data-map-add]');
  const valid=Number.isInteger(q)&&q>=1&&q<=100000000;button.disabled=!valid;button.dataset.mapQuantity=String(q);
  const host=box.querySelector('.map-custom-gaps');
  if(!valid){host.textContent='Enter a whole number from 1 to 100,000,000.';continue;}
  const id=box.dataset.mapCustomItem,gaps=visibleCraftMapGaps(craftMapCandidateGaps(items,mapPlan,state,mapDrafts,id,q));
  host.innerHTML=gaps.length?gaps.slice(0,2).map(([ref,n])=>`<button class="map-gap" data-map-choice-gap="${id}" data-map-custom="true" data-map-quantity="${q}" data-map-missing="${ref}">⚠ Supply ${mapCount(Math.ceil(n))} ${esc(items[ref].name)} →</button>`).join('')+(gaps.length>2?`<small>and ${gaps.length-2} more ingredients</small>`:''):'<p class="map-supplied">✓ Ingredients already supplied</p>';
 }
}
$('mapInspector').addEventListener('change',e=>{const box=e.target.closest('.map-custom-option');if(box&&e.target.matches('input'))mapRefreshCustomOptions(box);});
$('mapInspector').addEventListener('click',e=>{const preset=e.target.closest('[data-map-preset]');if(!preset)return;const box=preset.closest('.map-custom-option');box.querySelector('input').value=preset.dataset.mapPreset;mapRefreshCustomOptions(box);});
async function mapSources(id){
 const token=++mapCandidateToken,host=$('mapOptions');host.textContent='Checking exploration sources…';
 try{const {sources}=await api('/api/item/'+id);if(token!==mapCandidateToken)return;
 const rows=sources.filter(s=>s.kind==='explore'&&state.areas.includes(s.location_id)&&!s.conditions?.frozen&&Object.entries({ironDepot:state.iron_depot,runecube:state.runecube,manualFishing:false}).every(([k,v])=>s.conditions?.[k]==null||s.conditions[k]===v)).sort((a,b)=>b.expected_drops_per_explore-a.expected_drops_per_explore);
 host.innerHTML='<h4>Supply the shortage</h4><p class="hint">Select a source, then preview the whole plan. Existing route locations stay available; selected sources are the only additional locations allowed.</p>'+rows.map(r=>`<button class="map-candidate" data-map-area="${esc(r.location_id)}" data-map-source-item="${id}"><strong>${esc(r.location_name||r.location_id)}</strong><small>${fmt(r.expected_drops_per_explore)} items per explore · ${mapPlan.areas.some(a=>a.location_id===r.location_id)?'Explore more here':'Add this location'}</small></button>`).join('');
 if(!rows.length)host.innerHTML+='<p>No enabled exploration source. Bring this material from your farm or enable its area in Settings.</p>';
 }catch(e){if(token===mapCandidateToken)host.textContent=e.message;}
}
function mapNext(){
 if(!mapGraph)return;const counts={};for(const a of mapPlan.areas)for(const output of a.items)if(output.expected_drops>0)counts[output.item_id]=(counts[output.item_id]||0)+1;
 const candidates=mapGraph.nodes.filter(n=>n.kind==='item'&&n.stock>=1&&!n.primary&&!state.guided_skipped.includes(n.id)&&!n.voided&&!mapVisit.has(n.id));
 candidates.sort((a,b)=>(counts[a.id]||99)-(counts[b.id]||99)||b.stock-a.stock);
 const n=candidates[0];if(!n){mapVisit.clear();$('mapInspector').innerHTML='<h3>Current materials reviewed</h3><p>You can inspect any node, reveal other outputs from a location, or apply your proposed changes.</p>';return;}
 mapVisit.add(n.id);mapSelect(n.id);mapConsumers(n.id);mapFocus(n.id);
}
function mapFocus(id){const p=mapPositions[id];if(p)$('mapViewport').scrollTo({left:Math.max(0,p.x*mapScale-150),top:Math.max(0,p.y*mapScale-100),behavior:'smooth'});}
function mapZoom(scale){mapScale=Math.max(.2,Math.min(1.8,scale));$('mapCanvas').style.transform=`scale(${mapScale})`;$('mapStage').style.width=$('mapCanvas').offsetWidth*mapScale+'px';$('mapStage').style.height=$('mapCanvas').offsetHeight*mapScale+'px';}
$('mapZoomIn').onclick=()=>mapZoom(mapScale*1.2);$('mapZoomOut').onclick=()=>mapZoom(mapScale/1.2);
$('mapTower').oninput=$('mapTower').onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<0||n>10000)return;state.tower_level=n;save();if(mapSelected){mapSelect(mapSelected);mapConsumers(mapSelected);}};
$('mapNext').onclick=mapNext;
$('mapUnusedMode').onchange=e=>{state.map_unused_mode=e.target.value;save();mapRender();};
$('mapUnusedCount').onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>1000){e.target.value=state.map_unused_count??6;return;}state.map_unused_count=n;save();mapRender();};
$('mapExpand').onclick=()=>{const expanded=craftMap.classList.toggle('map-fullscreen');$('mapExpand').textContent=expanded?'Back to planner':'Open large map';if(expanded){mapZoom(.85);$('mapViewport').scrollTo(0,0);}};
$('mapReviewTop').onclick=()=>$('mapPreview').click();
$('mapNodes').onclick=e=>{const toggle=e.target.closest('[data-map-toggle-area]');if(toggle){const id=toggle.dataset.mapToggleArea,open=state.map_expanded_areas||[];state.map_expanded_areas=open.includes(id)?open.filter(a=>a!==id):[...open,id];save();mapRender();return;}const port=e.target.closest('[data-map-port]'),node=e.target.closest('[data-map-node]'),gap=e.target.closest('[data-map-gap]');if(!node)return;const id=node.dataset.mapNode;mapSelect(id);if(gap)mapSources(id);else if(port)mapConsumers(id);};
$('mapNodes').onkeydown=e=>{if(e.target.matches('[data-map-node]')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();mapSelect(e.target.dataset.mapNode);}};
$('mapInspector').onclick=async e=>{
 const jump=e.target.closest('[data-map-jump]');if(jump){mapSelect(jump.dataset.mapJump);mapFocus(jump.dataset.mapJump);return;}
 const gap=e.target.closest('[data-map-choice-gap]');if(gap){mapInspectDraft={item_id:gap.dataset.mapChoiceGap,cap:Number(gap.dataset.mapQuantity),allow_exploration:gap.dataset.mapCustom==='true',automatic_supply:gap.dataset.mapCustom==='true'};mapChanged();mapSelect(gap.dataset.mapMissing);mapFocus(gap.dataset.mapMissing);return;}
 const add=e.target.closest('[data-map-add]'),reveal=e.target.closest('[data-map-reveal]'),remove=e.target.closest('[data-map-remove]'),area=e.target.closest('[data-map-area]');
 if(add){mapInspectDraft=null;const id=add.dataset.mapAdd;if(state.targets[id]||state.secondary.some(g=>g.item_id===id)||mapDrafts.some(g=>g.item_id===id))return;if(state.secondary.length+mapDrafts.length>=20){$('mapOptions').textContent='The plan supports 20 leftover crafts. Remove one to continue.';return;}const custom=add.dataset.mapCustom==='true',box=add.closest('.map-custom-option');const cap=Number(box?box.querySelector('input').value:add.dataset.mapQuantity);if(!Number.isInteger(cap)||cap<1||cap>100000000)return;mapDrafts.push({item_id:id,cap,allow_exploration:custom,automatic_supply:custom,automatic_batch:true,available_only:add.dataset.mapAvailable==='true',void_source:add.dataset.mapAvailable==='true'?add.dataset.mapFocus:null});mapChanged();mapSelect(id);mapFocus(id);}
 if(reveal){state.map_hidden=state.map_hidden.filter(id=>id!==reveal.dataset.mapReveal);save();mapExpanded.add(reveal.dataset.mapReveal);mapRender();mapSelect(reveal.dataset.mapReveal);mapFocus(reveal.dataset.mapReveal);}
 if(remove){mapDrafts=mapDrafts.filter(g=>g.item_id!==remove.dataset.mapRemove);mapSelected=null;mapChanged();}
 if(area){if(mapInspectDraft&&!mapDrafts.some(g=>g.item_id===mapInspectDraft.item_id)){mapDrafts.push({...mapInspectDraft,automatic_batch:true});mapInspectDraft=null;}mapExtraAreas.add(area.dataset.mapArea);mapProposedLinks.push({from:'area:'+area.dataset.mapArea,to:area.dataset.mapSourceItem,quantity:mapGraph.missing[area.dataset.mapSourceItem]||0,phantom:true});const affected=craftMapDependents(items,mapDrafts,area.dataset.mapSourceItem);for(const g of mapDrafts)if(affected.includes(g.item_id)){g.allow_exploration=true;g.available_only=false;g.void_source=null;}mapChanged();$('mapOptions').innerHTML='<p>Calculating more exploration for these crafts. Your craft limits stay fixed.</p>';if(mapDrafts.length&&!mapBusy())await mapComputePreview(false);else $('mapOptions').innerHTML='<p>Add a proposed craft first, then choose a source for its missing ingredients.</p>';}
};
$('mapDiscard').onclick=()=>{if(mapOriginal){Object.assign(state,mapOriginal);mapOriginal=null;}mapJob++;if(mapPreviewRunning)browserPlanner.cancel();mapDrafts=[];mapInspectDraft=null;mapExtraAreas.clear();mapProposedLinks=[];mapSelected=null;mapChanged();};
let mapPreviewRunning=false;
$('mapPreview').onclick=()=>mapComputePreview(true);
async function mapComputePreview(showReview=false){
 if(showReview&&mapPreview&&mapRevision===revision){if(!$('mapReviewDialog').open)$('mapReviewDialog').showModal();return;}
 if(!mapChangeCount()||mapBusy()||mapPreviewRunning)return;mapInspectDraft=null;mapRender();const token=++mapJob;mapRevision=revision;mapPreview=null;mapPreviewRunning=true;$('mapPreview').disabled=true;$('mapReviewTop').disabled=true;$('mapSummary').textContent='Checking proposed crafts together…';$('mapPreviewResult').hidden=true;$('mapReviewStatus').textContent='Checking proposed crafts together…';if(showReview&&!$('mapReviewDialog').open)$('mapReviewDialog').showModal();
 const baseAreas=mapPlan.areas.map(a=>a.location_id),extra=[...new Set([...baseAreas,...mapExtraAreas])];
 try{const {job_id}=await api('/api/plan',{...guidePayload(),...(mapOriginal?{secondary:mapOriginal.secondary,replacement_goals:[...state.secondary,...mapDrafts].map(({item_id,cap,allow_exploration,automatic_batch,prioritize})=>({item_id,cap,allow_exploration,automatic_batch,prioritize}))}:{}),chosen_goals:mapDrafts.map(({item_id,cap,allow_exploration,automatic_batch})=>({item_id,cap,allow_exploration,automatic_batch})),automatic_areas:extra.length?extra:null});
 while(token===mapJob){if(mapRevision!==revision)throw Error('The plan changed. Preview the updated map again.');const job=await api('/api/jobs/'+job_id);if(job.status==='error')throw Error(job.error);if(job.status==='complete'){const shortfalls=job.result.outputs.filter(o=>{const g=mapDrafts.find(g=>g.item_id===o.item_id);return g&&!g.available_only&&g.cap-o.crafts>=10;});mapPreview={...job.result,areas:extra,shortfalls};mapRender();if(mapSelected)mapSelect(mapSelected);$('mapReviewStatus').textContent='';$('mapPreviewResult').hidden=false;$('mapPreviewResult').innerHTML=`<h3>Proposed route change</h3>${mapOriginal?`<p>Removed crafts: ${mapOriginal.secondary.filter(g=>!state.secondary.some(s=>s.item_id===g.item_id)).map(g=>esc(items[g.item_id].name)).join(', ')||'None'}. Other node and quantity changes are included.</p>`:''}<p><strong>${fmt(job.result.extra_explores)} extra explores · ${guidedExploreIncrease(job.result)}</strong> · ${fmt(job.result.total_explores)} total</p><p>New locations: ${job.result.new_locations.map(id=>esc(catalog.locations.find(a=>a.id===id)?.name||id)).join(', ')||'None'}</p><div class="map-preview-outputs">${job.result.outputs.map(o=>`<div>${itemName(o.item_id,items[o.item_id].name)}<strong>${mapCount(o.crafts)} crafts</strong><small>${mapCount(o.remaining)} left at the end</small></div>`).join('')}</div>${job.result.reduced.length?`<p class="externalnote">Existing crafts reduced: ${job.result.reduced.map(o=>`${esc(items[o.item_id].name)} ${mapCount(o.before)} → ${mapCount(o.after)}`).join('; ')}</p>`:''}<p class="hint">These are the amounts your updated route can make.</p>${shortfalls.length?`<p class="map-gap">Resolve shortages before applying: ${shortfalls.map(o=>`${esc(items[o.item_id].name)}: ${mapCount(o.crafts)} of ${mapCount(mapDrafts.find(g=>g.item_id===o.item_id).cap)} crafts`).join('; ')}. Close this review and choose a source on the map, or lower the craft limit.</p>`:''}<button class="primary" id="mapApply" ${shortfalls.length?'disabled':''}>Apply reviewed plan</button>`;$('mapApply').onclick=mapApply;if(showReview&&$('mapReviewDialog').open)$('mapApply').focus({preventScroll:true});$('mapSummary').textContent='Preview ready: '+mapCount(job.result.total_explores)+' explores. Apply in the review dialog to update your route.';return;}$('mapSummary').textContent=job.message||'Checking…';$('mapReviewStatus').textContent=job.message||'Checking…';await new Promise(r=>setTimeout(r,200));}
 }catch(e){if(token===mapJob){const message=e.message.split('\n').filter(Boolean).at(-1);$('mapSummary').textContent=message;$('mapReviewStatus').textContent=message;}}finally{if(token===mapJob){mapPreviewRunning=false;$('mapPreview').disabled=!mapChangeCount();$('mapReviewTop').disabled=!mapChangeCount();}}
};
async function mapApply(){if(!mapPreview||mapRevision!==revision||mapPreview.shortfalls?.length)return;$('mapReviewDialog').close();state.map_use_void=[...new Set([...state.map_use_void,...mapDrafts.filter(g=>g.available_only).map(g=>g.void_source).filter(Boolean)])];state.secondary=mapPreview.replacement?mapPreview.goals.map(g=>({...g})):[...state.secondary,...mapPreview.goals.map(g=>({...g}))];mapOriginal=null;state.automatic_areas=mapPreview.areas;mapDrafts=[];mapInspectDraft=null;mapExtraAreas.clear();mapPreview=null;$('mapPreviewResult').hidden=true;changed();clearTimeout(timer);await calculate();$('mapSummary').textContent='Plan updated. Use Save / load to keep a copy.';}
window.addEventListener('planner-result',mapRender);
window.addEventListener('planner-cleared',()=>{mapJob++;mapDrafts=[];mapPositions={};mapSelected=null;mapRender();});
window.addEventListener('planner-settings-saved',()=>{if(!mapGraph&&state){mapPositions=JSON.parse(JSON.stringify(state.map_positions||{}));$('mapTower').value=state.tower_level||0;}});
if(mapCurrent())mapRender();else craftMap.hidden=true;
